### ISSUE TITLE
Capitalization

### ISSUE THREAD

**Issue by 2016rshah** [hellerve/website#1]
Maybe this is a stylistic thing, but "My Resume" is camel case while "My blog" and "Contact me" are sentence case. Perhaps change resume to be lower case to make things more consistent or make everything camel case

**Comment by hellerve** [comment]
Heh, thank you. I am more in favor of capitalizing everything. Good catch!

**Comment by hellerve** [comment]
Done in `e9a6e88`. Deployed to the server. Thanks again!

**Comment by 2016rshah** [comment]
Cheers!
